spring.datasource.url= jdbc:postgresql://localhost:5432/motoshop_db
spring.datasource.username=postgres
spring.datasource.password=secret1234
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update

aes.secretKey = ${AES_SECRET_KEY:O8rxXAQPQtk0MSUl7ntHaffq9K+VddsW}
jwt.secretKey = ${JWT_SECRET_KEY:566B59703373357638792F423F4528482B4D6251655468576D5A713474377739}

logging.level.org.springframework.security.oauth2=DEBUG