
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update

aes.secretKey = ${AES_SECRET_KEY}
jwt.secretKey = ${JWT_SECRET_KEY}

logging.level.org.springframework.security.oauth2=DEBUG

