spring.application.name=auth-service

#spring.datasource.url= jdbc:postgresql://pms.cdy2k24omzsc.ap-southeast-1.rds.amazonaws.com:5433/mcrms_db
spring.datasource.url= jdbc:postgresql://localhost:5432/motoshop_db
spring.datasource.username=postgres
spring.datasource.password=secret1234
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update

aes.secretKey = O8rxXAQPQtk0MSUl7ntHaffq9K+VddsW

logging.level.org.springframework.security.oauth2=DEBUG
